In [73]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
data =  pd.read_excel("/Volumes/17194110228/projects/PycharmProjects汪雷/data.xlsx",sheet_name="C (2)")
# train_data = data
newdata = data[data["ΔS"].notna()].to_numpy()
X = newdata[:,1:5]
y = newdata[:,0]
print(X,y)
# 非线性回归
ployfeat1 = PolynomialFeatures(degree=1)  # 根据degree的值转换为相应的多项式（非线性回归）
ployfeat2 = PolynomialFeatures(degree=2)  # 根据degree的值转换为相应的多项式（非线性回归）
ployfeat3 = PolynomialFeatures(degree=3)  # 根据degree的值转换为相应的多项式（非线性回归）

model1 = LinearRegression()
model1.fit(ployfeat1.fit_transform(X), y)
model1.predict(ployfeat1.fit_transform(X)),y

model2 = LinearRegression()
model2.fit(ployfeat2.fit_transform(X), y)
model2.predict(ployfeat2.fit_transform(X)),y

model3 = LinearRegression()
model3.fit(ployfeat3.fit_transform(X), y)
model3.predict(ployfeat3.fit_transform(X)),y

[[-5.000e-04 -5.932e-01  1.000e-02  5.070e-01]
 [-1.680e-02 -6.964e-01  1.000e-02  4.040e-01]
 [ 4.000e-04 -6.451e-01  1.000e-02  4.550e-01]
 [-3.330e-02 -6.413e-01  1.000e-02  4.590e-01]
 [ 5.000e-04 -8.220e-02  1.000e-02  9.530e-01]
 [-2.100e-03  1.304e-01  1.000e-02  1.024e+00]
 [-3.000e-04 -1.652e-01  1.000e-02  9.190e-01]
 [-5.000e-04 -1.800e-01  1.000e-02  9.110e-01]
 [-8.000e-04 -1.881e-01  1.000e-02  9.360e-01]
 [-1.690e-02 -7.160e-02  1.000e-02  9.270e-01]
 [-1.810e-02 -4.530e-02  1.000e-02  9.340e-01]
 [-1.370e-02 -5.490e-02  1.000e-02  9.160e-01]
 [-2.600e-03  2.150e-02  1.000e-02  1.021e+00]
 [-1.000e-04 -4.530e-02  1.000e-02  9.550e-01]
 [-3.100e-03  1.026e-01  1.000e-02  1.247e+00]] [ 107.2  160.6  179.2 -290.3   49.3   78.7   66.4  -17.9   -9.4  -52.2
 -106.   189.4 -160.8 -427.1 -351.4]


(array([ 107.2,  160.6,  179.2, -290.3,   49.3,   78.7,   66.4,  -17.9,
          -9.4,  -52.2, -106. ,  189.4, -160.8, -427.1, -351.4]),
 array([ 107.2,  160.6,  179.2, -290.3,   49.3,   78.7,   66.4,  -17.9,
          -9.4,  -52.2, -106. ,  189.4, -160.8, -427.1, -351.4]))

In [79]:
import numpy as np
# 填充数据
# data.loc(1)[:
data =  pd.read_excel("/Volumes/17194110228/projects/PycharmProjects汪雷/data.xlsx",sheet_name="C (2)")
test_X = data[data["ΔS"].isna()][['lnr','△EA','Wt','RCE*']].to_numpy()

result = model2.predict(ployfeat2.fit_transform(test_X))
i = 0
for index,r in enumerate(data["ΔS"]):
    if pd.isna(r):
        if result[i]>=1000 or result[i] <=-1000:
            result[i] = model3.predict(ployfeat3.fit_transform(test_X))[i]
            if result[i]>=1000 or result[i] <=-1000:
                result[i] = model1.predict(ployfeat1.fit_transform(test_X))[i]
        data["ΔS"][index] = result[i]
        i = i + 1

data.to_csv("./generate.csv",index=False)
# for index,r in enumerate(data["ΔS"]):
#     print(r,data["ΔS"].isna)
#     if data["ΔS"][index].isna():
#         print("true")